/**
 * SongDisplay.jsx
 * Final song display — full formatted lyrics, metadata, copy/export options.
 */
import { useState } from 'react'
import styles from './SongDisplay.module.css'

const SECTION_COLORS = {
  verse: '#7c3aed', hook: '#f59e0b', 'pre-hook': '#f97316',
  bridge: '#10b981', intro: '#6b7280', outro: '#3b82f6',
}

export default function SongDisplay({ song, analysis, onRestart }) {
  const [copied, setCopied] = useState(false)
  const [view,   setView]   = useState('sections') // 'sections' | 'plain'

  function copyToClipboard() {
    navigator.clipboard.writeText(song.song).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  function downloadTxt() {
    const meta = [
      `SONG — Generated by SCI (Structured Creative Intelligence)`,
      `Archetype:    ${song.metadata.archetype}`,
      `Core Message: ${song.metadata.coreMessage}`,
      `Language:     ${song.metadata.language}`,
      `Structure:    ${song.metadata.structure}`,
      `Generated:    ${new Date().toLocaleString()}`,
      '',
      '═'.repeat(50),
      '',
      song.song,
    ].join('\n')

    const blob = new Blob([meta], { type: 'text/plain' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = `sci-song-${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className={styles.page}>
      <div className={styles.content}>
        {/* Header */}
        <div className={styles.hero}>
          <div className={styles.heroBadge}>◈ SCI Generated</div>
          <h2 className={styles.archetype}>{song.metadata.archetype}</h2>
          <p className={styles.coreMsg}>"{song.metadata.coreMessage}"</p>
          <div className={styles.metaRow}>
            <span className={styles.metaTag}>{song.metadata.language}</span>
            <span className={styles.metaTag}>{song.metadata.structure?.replace(/_/g, ' ')}</span>
            <span className={styles.metaTag}>{song.sections.length} sections</span>
          </div>
        </div>

        {/* View toggle */}
        <div className={styles.viewToggle}>
          <button
            className={[styles.viewBtn, view === 'sections' ? styles.viewActive : ''].join(' ')}
            onClick={() => setView('sections')}
          >Structured View</button>
          <button
            className={[styles.viewBtn, view === 'plain' ? styles.viewActive : ''].join(' ')}
            onClick={() => setView('plain')}
          >Plain Text</button>
        </div>

        {/* Song body */}
        <div className={styles.songBody}>
          {view === 'sections' ? (
            song.sections.map((section, i) => (
              <div key={i} className={styles.sectionCard}>
                <div className={styles.sectionMeta}>
                  <span
                    className={styles.sectionType}
                    style={{ '--c': SECTION_COLORS[section.type] || '#7c3aed' }}
                  >
                    {section.type.toUpperCase()}
                  </span>
                  <span className={styles.sectionGoal}>
                    {section.goal?.replace(/_/g, ' ')}
                  </span>
                </div>
                <pre className={styles.lyrics}>{section.lyrics}</pre>
              </div>
            ))
          ) : (
            <pre className={styles.plainLyrics}>{song.song}</pre>
          )}
        </div>

        {/* Actions */}
        <div className={styles.actions}>
          <button className={styles.copyBtn} onClick={copyToClipboard}>
            {copied ? '✓ Copied!' : '⎘ Copy Lyrics'}
          </button>
          <button className={styles.downloadBtn} onClick={downloadTxt}>
            ↓ Download .txt
          </button>
          <button className={styles.restartBtn} onClick={onRestart}>
            ↺ Write Another Song
          </button>
        </div>

        {/* Persona reminder */}
        <div className={styles.footer}>
          <p className={styles.footerNote}>
            Built with <strong>SCI</strong> — Structured Creative Intelligence.
            Identity → Persona → Message → Structure → Song.
          </p>
        </div>
      </div>
    </div>
  )
}
